In [2]:
import pandas as pd
import numpy as np

In [4]:
worldBank = pd.read_csv('../Data/WorldBank/GDP_WB/d68753d7-ae7d-430a-a598-20f1c7cc58f9_Data.csv')
vDemDataSet = pd.read_csv('../Data/Country_Date_V-Dem_CSV_v11/Country_Date_V-Dem_CSV_v11/V-Dem-CD-v11.csv')
# vDemDataSet = vDemDataSet[vDemDataSet["year"] >= 1959]
polity5Data = pd.read_excel('../Data/Polity5/p5v2018.xls')

c:\Users\Thoma\.conda\envs\thesisProject\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (364,365,366,394,410,821,831,832,930,1233,1250,1479,3071,3290,3291,3346,3348,3352,3353,3355,3356,3357) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
vDemDataSet.describe()

,country_id,year,project,historical,codingstart,codingend,codingstart_contemp,codingend_contemp,codingstart_hist,codingend_hist,...,v2smorgtypes_1,v2smorgtypes_2,v2smorgtypes_3,v2smorgtypes_4,v2smorgtypes_5,v2smorgtypes_6,v2smorgtypes_7,v2smorgtypes_8,v2smorgtypes_9,v2smorgtypes_nr
count,74888.000000,74888.000000,74888.000000,74888.000000,74888.000000,74888.000000,71571.000000,71571.000000,45435.000000,45435.000000,...,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000,3743.000000
mean,105.042771,1932.130755,0.399450,0.606706,1843.885255,2012.690271,1906.682399,2019.491763,1799.442038,1918.433014,...,0.563484,0.685099,0.393227,0.144277,0.075181,0.079468,0.067158,0.022206,0.094823,6.297088
std,79.657584,62.993398,0.600529,0.488484,59.278207,31.943127,17.772172,4.740047,20.179824,18.121196,...,0.246276,0.262522,0.265438,0.179781,0.140251,0.133389,0.140443,0.079129,0.149116,1.789246
min,3.000000,1789.000000,0.000000,0.000000,1789.000000,1859.000000,1900.000000,1948.000000,1789.000000,1859.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,45.000000,1889.000000,0.000000,0.000000,1789.000000,2020.000000,1900.000000,2020.000000,1789.000000,1920.000000,...,0.400000,0.500000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000
50%,90.000000,1943.000000,0.000000,1.000000,1817.000000,2020.000000,1900.000000,2020.000000,1789.000000,1920.000000,...,0.571000,0.714000,0.400000,0.091000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
75%,155.000000,1986.000000,1.000000,1.000000,1900.000000,2020.000000,1900.000000,2020.000000,1800.000000,1920.000000,...,0.750000,0.875000,0.571000,0.250000,0.125000,0.143000,0.125000,0.000000,0.167000,8.000000
max,373.000000,2020.000000,2.000000,1.000000,2011.000000,2020.000000,2011.000000,2020.000000,1878.000000,2010.000000,...,1.000000,1.000000,1.000000,1.000000,0.833000,0.900000,1.000000,0.750000,1.000000,12.000000

In [3]:
worldBankDict = dict(zip(worldBank['Country Name'], worldBank['Country Code']))
polityVDict = dict(zip(polity5Data['country'], polity5Data['scode']))
vDem = dict(zip(vDemDataSet['country_name'], vDemDataSet['country_text_id']))

auxillaryDictionary = {
    'Hong Kong':'HKG',
    "Bosnia":'BIH',
    'Burma/Myanmar':'MMR',
    'Egypt':'EGY',
    'Gambia':'GMB',
    'The Gambia':'GMB',
    'Democratic Republic of the Congo':'COD',
    'Iran':'IRN',
    'Korea North': 'PRK',
    'North Korea': 'PRK',
    'Korea South':'KOR',
    'South Korea': 'KOR',
    'Laos':'LAO',
    'Congo Brazzaville':'COG',
    'Congo Kinshasa':'COD',
    'Republic of the Congo':'COG',
    'Congo-Brazzaville': 'COG',
    "Cote D'Ivoire":'CIV',
    'Ivory Coast': 'CIV',
    'Yemen':'YEM',
    "United Kingdom":'GBR',
    "Cote D'Ivoire":'CIV',
    'Kyrgyzstan':'KGZ',
    'Myanmar (Burma)':'MMR',
    'Macedonia':'MKD',
    'Korea':'KOR',
    'Republic of Vietnam':'VNM',
    'Czechoslovakia':'CZE',
    'Cape Verde':'CPV',
    'Germany West':'DEU',
    'Russia':'RUS',
    'Syria':'SYR',
    'Slovakia':'SVK',
    'Slovak Republic':'SVK',
    'UAE':'ARE',
    'Timor Leste':'TLS',
    'United States                   ':'USA',
    'United States of America':'USA',
    'Venezuela':'VEN'
}

In [4]:
countryDictionary = {**polityVDict,**vDem, **auxillaryDictionary}
worldBankPlusDictionary = { **auxillaryDictionary, **worldBankDict}

In [5]:
set1 = set(countryDictionary.items())
set2 = set(worldBankPlusDictionary.items())

set1 - set2

{('Baden', 'BAD'),
 ('Bavaria', 'BAV'),
 ('German Democratic Republic', 'DDR'),
 ('Germany East', 'GDR'),
 ('Gran Colombia', 'GCL'),
 ('Modena', 'MOD'),
 ('Orange Free State', 'OFS'),
 ('Palestine/Gaza', 'PSG'),
 ('Palestine/West Bank', 'PSE'),
 ('Papal States', 'PAP'),
 ('Parma', 'PMA'),
 ('Prussia', 'GMY'),
 ('Sardinia', 'SAR'),
 ('Saxony', 'SAX'),
 ('Serbia and Montenegro', 'YGS'),
 ('Somaliland', 'SML'),
 ('South Vietnam', 'RVN'),
 ('South Yemen', 'YMD'),
 ('Sudan-North', 'SDN'),
 ('Swaziland', 'SWA'),
 ('Taiwan', 'TWN'),
 ('Tuscany', 'TUS'),
 ('Two Sicilies', 'SIC'),
 ('USSR', 'USR'),
 ('United Province CA', 'UPC'),
 ('Vietnam North', 'DRV'),
 ('Wuerttemburg', 'WRT'),
 ('Yemen North', 'YAR'),
 ('Yemen South', 'YPR'),
 ('Yugoslavia', 'YUG'),
 ('Zanzibar', 'ZZB')}

In [6]:
set2 - set1

{("Cote d'Ivoire", 'CIV'),
 ("Korea, Dem. People's Rep.", 'PRK'),
 ('Africa Eastern and Southern', 'AFE'),
 ('Africa Western and Central', 'AFW'),
 ('American Samoa', 'ASM'),
 ('Andorra', 'AND'),
 ('Antigua and Barbuda', 'ATG'),
 ('Arab World', 'ARB'),
 ('Aruba', 'ABW'),
 ('Bahamas, The', 'BHS'),
 ('Belize', 'BLZ'),
 ('Bermuda', 'BMU'),
 ('British Virgin Islands', 'VGB'),
 ('Brunei Darussalam', 'BRN'),
 ('Cabo Verde', 'CPV'),
 ('Caribbean small states', 'CSS'),
 ('Cayman Islands', 'CYM'),
 ('Central Europe and the Baltics', 'CEB'),
 ('Channel Islands', 'CHI'),
 ('Congo, Dem. Rep.', 'COD'),
 ('Congo, Rep.', 'COG'),
 ('Curacao', 'CUW'),
 ('Dominica', 'DMA'),
 ('Early-demographic dividend', 'EAR'),
 ('East Asia & Pacific (IDA & IBRD countries)', 'TEA'),
 ('East Asia & Pacific (excluding high income)', 'EAP'),
 ('East Asia & Pacific', 'EAS'),
 ('Egypt, Arab Rep.', 'EGY'),
 ('Euro area', 'EMU'),
 ('Europe & Central Asia (IDA & IBRD countries)', 'TEC'),
 ('Europe & Central Asia (excluding high income)', 'ECA'),
 ('Europe & Central Asia', 'ECS'),
 ('European Union', 'EUU'),
 ('Faroe Islands', 'FRO'),
 ('Fragile and conflict affected situations', 'FCS'),
 ('French Polynesia', 'PYF'),
 ('Gambia, The', 'GMB'),
 ('Gibraltar', 'GIB'),
 ('Greenland', 'GRL'),
 ('Grenada', 'GRD'),
 ('Guam', 'GUM'),
 ('Heavily indebted poor countries (HIPC)', 'HPC'),
 ('High income', 'HIC'),
 ('Hong Kong SAR, China', 'HKG'),
 ('IBRD only', 'IBD'),
 ('IDA & IBRD total', 'IBT'),
 ('IDA blend', 'IDB'),
 ('IDA only', 'IDX'),
 ('IDA total', 'IDA'),
 ('Iran, Islamic Rep.', 'IRN'),
 ('Isle of Man', 'IMN'),
 ('Kiribati', 'KIR'),
 ('Korea, Rep.', 'KOR'),
 ('Kyrgyz Republic', 'KGZ'),
 ('Lao PDR', 'LAO'),
 ('Late-demographic dividend', 'LTE'),
 ('Latin America & Caribbean (excluding high income)', 'LAC'),
 ('Latin America & Caribbean', 'LCN'),
 ('Latin America & the Caribbean (IDA & IBRD countries)', 'TLA'),
 ('Least developed countries: UN classification', 'LDC'),
 ('Liechtenstein', 'LIE'),
 ('Low & middle income', 'LMY'),
 ('Low income', 'LIC'),
 ('Lower middle income', 'LMC'),
 ('Macao SAR, China', 'MAC'),
 ('Marshall Islands', 'MHL'),
 ('Micronesia, Fed. Sts.', 'FSM'),
 ('Middle East & North Africa (IDA & IBRD countries)', 'TMN'),
 ('Middle East & North Africa (excluding high income)', 'MNA'),
 ('Middle East & North Africa', 'MEA'),
 ('Middle income', 'MIC'),
 ('Monaco', 'MCO'),
 ('Myanmar', 'MMR'),
 ('Nauru', 'NRU'),
 ('New Caledonia', 'NCL'),
 ('North America', 'NAC'),
 ('Northern Mariana Islands', 'MNP'),
 ('Not classified', 'INX'),
 ('OECD members', 'OED'),
 ('Other small states', 'OSS'),
 ('Pacific island small states', 'PSS'),
 ('Palau', 'PLW'),
 ('Post-demographic dividend', 'PST'),
 ('Pre-demographic dividend', 'PRE'),
 ('Puerto Rico', 'PRI'),
 ('Russian Federation', 'RUS'),
 ('Samoa', 'WSM'),
 ('San Marino', 'SMR'),
 ('Sint Maarten (Dutch part)', 'SXM'),
 ('Small states', 'SST'),
 ('South Asia (IDA & IBRD)', 'TSA'),
 ('South Asia', 'SAS'),
 ('St. Kitts and Nevis', 'KNA'),
 ('St. Lucia', 'LCA'),
 ('St. Martin (French part)', 'MAF'),
 ('St. Vincent and the Grenadines', 'VCT'),
 ('Sub-Saharan Africa (IDA & IBRD countries)', 'TSS'),
 ('Sub-Saharan Africa (excluding high income)', 'SSA'),
 ('Sub-Saharan Africa', 'SSF'),
 ('Syrian Arab Republic', 'SYR'),
 ('Tonga', 'TON'),
 ('Turks and Caicos Islands', 'TCA'),
 ('Tuvalu', 'TUV'),
 ('United States', 'USA'),
 ('Upper middle income', 'UMC'),
 ('Venezuela, RB', 'VEN'),
 ('Virgin Islands (U.S.)', 'VIR'),
 ('West Bank and Gaza', 'PSE'),
 ('World', 'WLD'),
 ('Yemen, Rep.', 'YEM'),
 (nan, nan)}

In [7]:
totalCountryDictionary = {**polityVDict,**vDem, **auxillaryDictionary, **worldBankDict}

In [8]:
polity5Data["baseLineCountryCode"] = polity5Data['country'].replace(totalCountryDictionary)
vDemDataSet["baseLineCountryCode"] = vDemDataSet['country_name'].replace(totalCountryDictionary)

In [9]:
polity5Data["year"] = pd.to_numeric(polity5Data["year"])

In [10]:
polity5Data = polity5Data[polity5Data["year"] >= 1960 & polity5Data["baseLineCountryCode"].isin(worldBankDict.values())]

In [11]:
vDemDataSet = vDemDataSet[vDemDataSet["year"] >= 1960 & vDemDataSet["baseLineCountryCode"].isin(worldBankDict.values())]

In [12]:
politySubsection = polity5Data[["democ","autoc",'polity','polity2', 'baseLineCountryCode','year']]
politySubsection["democ"] = politySubsection["democ"]/10
politySubsection["autoc"] = politySubsection["autoc"]/10
politySubsection["polity"] = (politySubsection["polity"]+10)/10
politySubsection["polity2"] = (politySubsection["polity2"]+10)/10

<ipython-input-12-f9aac584712d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  politySubsection["democ"] = politySubsection["democ"]/10
<ipython-input-12-f9aac584712d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  politySubsection["autoc"] = politySubsection["autoc"]/10
<ipython-input-12-f9aac584712d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  politySubsection["polity"] = (politySubsection["polity"]+10)/10
<ipython-input-12-f9aac584712d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  politySubsection["polity2"] = (politySubsection["polity2"]+10)/10

In [13]:
politySubsection

       democ  autoc  polity  polity2 baseLineCountryCode  year
0        0.1    0.7     0.4      0.4                 AFG  1800
1        0.1    0.7     0.4      0.4                 AFG  1801
2        0.1    0.7     0.4      0.4                 AFG  1802
3        0.1    0.7     0.4      0.4                 AFG  1803
4        0.1    0.7     0.4      0.4                 AFG  1804
...      ...    ...     ...      ...                 ...   ...
17569    0.5    0.1     1.4      1.4                 ZWE  2014
17570    0.5    0.1     1.4      1.4                 ZWE  2015
17571    0.5    0.1     1.4      1.4                 ZWE  2016
17572    0.5    0.1     1.4      1.4                 ZWE  2017
17573    0.5    0.1     1.4      1.4                 ZWE  2018

[17574 rows x 6 columns]

In [14]:
vDemSubsection = vDemDataSet[["v2x_polyarchy","v2x_libdem","v2x_partipdem","v2x_delibdem","v2x_egaldem","year","baseLineCountryCode"]]
vDemSubsection = vDemSubsection.groupby(["baseLineCountryCode","year"]).agg(['last']).reset_index()

In [15]:
Y = politySubsection.merge(vDemSubsection,how="outer", sort=True)

In [16]:
columnNames = {'baseLineCountryCode':'country'}
Y = Y.rename(columns=columnNames)

In [17]:
Y.to_csv('y.csv', index=False)